name: _beautifulOS Prebuild Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sbsigntool mtools

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-uefi

      - name: Compile and Package
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Restore Keys
        run: |
          echo ${{ secrets.DB_KEY }} | base64 -d > docs/secure_boot/keys/db.key
          echo ${{ secrets.DB_CRT }} | base64 -d > docs/secure_boot/keys/db.crt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: beautifulOS-genesis-artifact
          path: beautifulOS.img
